### ISSUE TITLE
Save setting between sessions?

### ISSUE THREAD

**Issue by hasnogaems** [fury-sim/bugtracker#24]
Currently seems like I can build my char close the tab and it will be gone.

**Comment by fury-sim** [comment]
@hasnogaems unfortiounately i'm not allowed to save stuff in the sim like i did on the downloadable version. If you click the "Save Settings"-button it will however download a settings file that is put into your Downloads-folder. The next time you open the sim you could click "Load Settings" and select that file. Then everything should be as it used to be :)
